"""
Loom
Canonical Dream Schema — CCP v0.1

This is the universal data contract between all source apps and the engine.
No adapter should pass anything outside this schema to the engine.
"""

from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime
import uuid


# Stable namespace for deterministic UUIDs
# All adapters use this so the same source record always produces the same dream_id
CCP_NAMESPACE = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")


def make_dream_id(source_app: str, local_id: str) -> str:
    """
    Generate a stable, globally unique dream_id from source app + local identifier.
    Deterministic: same input always produces same UUID.
    Safe for backfill: re-running never creates duplicates.

    Examples:
        make_dream_id("browser_atlas", "sc:1234")
        make_dream_id("lab", "sc:42")
        make_dream_id("oneiro", "041e618b-0a85-4d1c-ae61-c98008083728")
    """
    return str(uuid.uuid5(CCP_NAMESPACE, f"{source_app}:{local_id}"))


def make_parent_id(source_app: str, dream_local_id: str) -> str:
    """
    Generate stable parent_dream_id (the night/dream session, not the cycle).
    Used to group sleep cycles that belong to the same night.
    """
    return str(uuid.uuid5(CCP_NAMESPACE, f"{source_app}:d:{dream_local_id}"))


# ---------------------------------------------------------------------------
# Canonical Dream Object
# ---------------------------------------------------------------------------

@dataclass
class DreamMetadata:
    lucid: Optional[bool] = None
    sleep_quality: Optional[int] = None        # 1-5 where available
    tags: list[str] = field(default_factory=list)
    emotions: list[str] = field(default_factory=list)

    # Extended fields — populated by adapters when source data supports it
    vividness: Optional[str] = None            # e.g. "vivid", "faint"
    emotional_tone: Optional[str] = None       # e.g. "neutral", "positive"
    is_nightmare: Optional[bool] = None
    is_recurring: Optional[bool] = None
    method: Optional[str] = None               # lucid induction method
    stability_score: Optional[int] = None      # LucidLab specific
    duration_estimate: Optional[int] = None    # minutes, LucidLab specific

    # Source-specific extras — preserved but not processed by engine
    extras: dict = field(default_factory=dict)


@dataclass
class CanonicalDream:
    """
    Universal dream object. Every adapter maps its source data into this.
    The engine operates exclusively on this structure.
    """
    # --- Required fields ---
    dream_id: str           # stable UUID5, generated by make_dream_id()
    source_app: str         # "browser_atlas" | "lab" | "oneiro"
    timestamp: str          # ISO-8601
    content: str            # full dream text
    language: str           # "sl" | "en" | "other"

    # --- Optional fields ---
    title: Optional[str] = None
    parent_dream_id: Optional[str] = None   # groups sleep cycles from same night
    cycle_index: Optional[int] = None       # position within night (1, 2, 3...)
    metadata: DreamMetadata = field(default_factory=DreamMetadata)

    # --- Internal tracking ---
    ingested_at: Optional[str] = None       # when engine received this dream
    source_updated_at: Optional[str] = None # last modification in source app

    def is_valid(self) -> bool:
        """Minimal validation before sending to engine."""
        return bool(
            self.dream_id
            and self.source_app
            and self.timestamp
            and self.content
            and self.content.strip()
            and self.language
        )

    def to_dict(self) -> dict:
        return {
            "dream_id": self.dream_id,
            "source_app": self.source_app,
            "timestamp": self.timestamp,
            "title": self.title,
            "content": self.content,
            "language": self.language,
            "parent_dream_id": self.parent_dream_id,
            "cycle_index": self.cycle_index,
            "metadata": {
                "lucid": self.metadata.lucid,
                "sleep_quality": self.metadata.sleep_quality,
                "tags": self.metadata.tags,
                "emotions": self.metadata.emotions,
                "vividness": self.metadata.vividness,
                "emotional_tone": self.metadata.emotional_tone,
                "is_nightmare": self.metadata.is_nightmare,
                "is_recurring": self.metadata.is_recurring,
                "method": self.metadata.method,
                "stability_score": self.metadata.stability_score,
                "duration_estimate": self.metadata.duration_estimate,
                "extras": self.metadata.extras,
            },
            "ingested_at": self.ingested_at,
            "source_updated_at": self.source_updated_at,
        }
